version: 0.2
proxy:
  upload-artifacts: yes
  logs: yes
phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip -O terraform.zip
      - unzip ./terraform.zip -d /usr/local/bin/
  build:
    commands:
      - terraform init
      - terraform workspace select $BUILD_ENV
      - terraform validate -var-file="variables/$BUILD_ENV.tfvars" 
      - terraform plan -var-file="variables/$BUILD_ENV.tfvars" -out="tfplan"
      - terraform apply "tfplan"
artifacts:
  files:
    -  tfplan
